// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Product { id: string, name: string, price: number, }

export interface User { id: string, email: string, username: string, created_at: string, updated_at: string, }

export interface CreateUserRequest { email: string, username: string, password: string, }

export interface LoginRequest { email: string, password: string, }

export interface AuthResponse { user: User, token: string, }

export interface ApiError { message: string, code: number, }